# Generated by Django 5.2.1 on 2025-06-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("public", "Опубликовано"), ("unpublic", "Не опубликовано")],
                default="unpublic",
                max_length=20,
                verbose_name="Статус публикации",
            ),
        ),
    ]
